# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :docker_master do |dm|
    dm.vm.box = "centos-7.1706_v0.2.0"
    dm.vm.network :private_network, ip: "192.168.56.101"
    dm.vm.provider :virtuadmox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "dm_server" ]
    end
    dm.vm.provision "shell", inline: <<-SHELL
      curl -fsSL get.docker.com -o get-docker.sh
      sh get-docker.sh
      usermod -aG docker vagrant
      systemctl start docker
      curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
    SHELL
  end
  config.vm.define :docker_node_1 do |dn1|
    dn1.vm.box = "centos-7.1706_v0.2.0"
    dn1.vm.network :private_network, ip: "192.168.56.102"
    dn1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "dn_node_1" ]
    end
    dn1.vm.provision "shell", inline: <<-SHELL
      curl -fsSL get.docker.com -o get-docker.sh
      sh get-docker.sh
      usermod -aG docker vagrant
      systemctl start docker
    SHELL
  end
  config.vm.define :docker_node_2 do |dn2|
    dn2.vm.box = "centos-7.1706_v0.2.0"
    dn2.vm.network :private_network, ip: "192.168.56.103"
    dn2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "dn_node_2" ]
    end
    dn2.vm.provision "shell", inline: <<-SHELL
      curl -fsSL get.docker.com -o get-docker.sh
      sh get-docker.sh
      usermod -aG docker vagrant
      systemctl start docker
    SHELL
  end
end
