FROM centos:7

LABEL author="Daniel Barragan"
LABEL image_name="base container for services"
LABEL description="container for installing services"

RUN yum install https://centos7.iuscommunity.org/ius-release.rpm -y

