 version: '2'
 services:
   web:
     image: compose_flask 
     #build: .
     ports:
      - "5000:5000"
     volumes:
      - .:/code
     depends_on:
      - redis
   redis:
     image: redis:3.0.7
