version: '3'
services:
  worker:
    image: nginx 
    ports:
      - "8000:80"
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
