FROM centos:7
LABEL author="Daniel Barragan"
LABEL image_name="artifact_builder"
LABEL description="Builder Image"

RUN yum install https://centos7.iuscommunity.org/ius-release.rpm -y
RUN yum install rpm-build python36u python36u-pip -y

